# Generated by Django 6.0.3 on 2026-03-12 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de l'entreprise"
                    ),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="Capacité (MW)")),
                (
                    "installation_type",
                    models.CharField(
                        choices=[
                            ("csp", "CSP"),
                            ("bifacial", "Bifacial PV"),
                            ("monofacial", "Monofacial PV"),
                            ("hybrid", "Hybride"),
                        ],
                        max_length=20,
                        verbose_name="Type d'installation",
                    ),
                ),
                ("province", models.CharField(max_length=100, verbose_name="Province")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email professionnel"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=255, verbose_name="Nom du contact"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("completed", "Complété")],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut de paiement",
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "En attente de paiement"),
                            ("pending_activation", "En attente d'activation"),
                            ("active", "Actif"),
                        ],
                        default="pending_payment",
                        max_length=20,
                        verbose_name="Statut du compte",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "ordering": ["-created_at"],
            },
        ),
    ]
