# Generated by Django 6.0.3 on 2026-03-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="password",
            field=models.CharField(
                default="temp", max_length=128, verbose_name="Mot de passe"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email professionnel"
            ),
        ),
    ]
