# Generated by Django 6.0.3 on 2026-03-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0002_enterprise_password_alter_enterprise_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="email_verification_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Code de vérification"
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="pending_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email en attente"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "En attente de paiement"),
                    ("pending_activation", "En attente d'activation"),
                    ("active", "Actif"),
                    ("cancelled", "Résilié"),
                ],
                default="pending_payment",
                max_length=20,
                verbose_name="Statut du compte",
            ),
        ),
    ]
